server:
  port: 80
spring:
  application:
    name: cloud-consumer-feign
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka1.com:7001/eureka,http://eureka2.com:7002/eureka
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com.moxuan.cloud.consumer.feign.order.service.PaymentService: debug