server:
  port: 9001
  # 因为当前 eureka 是单机版本，所以我们需要做一些配置
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://${eureka.instance.hostname}:9002/eureka/





