server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: 123456
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 9000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 10
      pool-name: DemoHikariCP

eureka:
  client:
    # 注册
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1.com:7001/eureka,http://eureka2.com:7002/eureka
  # 配置eureka 页面查看 ip(主机名修改) 重命名
  instance:
    instance-id: payment8001
    # 访问路径可以显示ip 地址
    prefer-ip-address: true

    # 客户端向服务发送心跳时间间隔  默认 30秒
    lease-renewal-interval-in-seconds: 1
    # 服务端在收到最后一次心跳后 等待的时间上线   超时删除
    lease-expiration-duration-in-seconds: 2