server:
  port: 9002

spring:
  application:
    name: cloud-alibaba-nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:1111
#        server-addr: 127.0.0.1:8848
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'