server:
  port: 84
spring:
  application:
    name: cloud-alibaba-consumer-nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

service-url:
  nacos-user-service: http://cloud-alibaba-nacos-provider-payment

feign:
  sentinel:
    enabled: true