server:
  port: 84
spring:
  application:
    name: cloud-alibaba-consumer-nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

service-url:
  nacos-user-service: http://cloud-alibaba-nacos-provider-payment
